---
# backend-randomer
- name: stop backend-randomer.service
  systemd:
    name: backend-randomer.service
    state: stopped
    enabled: false
  when: "node_alias == 'node2'"

- name: stop backend-randomer-sidecar-proxy.service
  systemd:
    name: backend-randomer-sidecar-proxy.service
    state: stopped
    enabled: false
  when: "node_alias == 'node2'"
